// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mozi.Server.Data;

#nullable disable

namespace Mozi.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220414191630_feltolt")]
    partial class feltolt
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Mozi.Shared.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("Ertekeles")
                        .HasColumnType("float");

                    b.Property<string>("Gyarto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Filmek");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ertekeles = 6.0,
                            Gyarto = "Lászlo és a fia",
                            Nev = "Elso film"
                        },
                        new
                        {
                            Id = 2,
                            Ertekeles = 8.0,
                            Gyarto = "Profi gyártó",
                            Nev = "Masodik film"
                        });
                });

            modelBuilder.Entity("Mozi.Shared.Szek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Foglalt")
                        .HasColumnType("bit");

                    b.Property<int>("Szam")
                        .HasColumnType("int");

                    b.Property<int>("TeremId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeremId");

                    b.ToTable("Szekek");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Foglalt = false,
                            Szam = 1,
                            TeremId = 1
                        },
                        new
                        {
                            Id = 2,
                            Foglalt = false,
                            Szam = 2,
                            TeremId = 1
                        },
                        new
                        {
                            Id = 3,
                            Foglalt = false,
                            Szam = 3,
                            TeremId = 1
                        },
                        new
                        {
                            Id = 4,
                            Foglalt = true,
                            Szam = 4,
                            TeremId = 1
                        },
                        new
                        {
                            Id = 5,
                            Foglalt = true,
                            Szam = 5,
                            TeremId = 1
                        },
                        new
                        {
                            Id = 6,
                            Foglalt = true,
                            Szam = 6,
                            TeremId = 1
                        },
                        new
                        {
                            Id = 7,
                            Foglalt = false,
                            Szam = 7,
                            TeremId = 1
                        },
                        new
                        {
                            Id = 9,
                            Foglalt = false,
                            Szam = 9,
                            TeremId = 1
                        },
                        new
                        {
                            Id = 10,
                            Foglalt = false,
                            Szam = 10,
                            TeremId = 1
                        },
                        new
                        {
                            Id = 11,
                            Foglalt = false,
                            Szam = 11,
                            TeremId = 1
                        },
                        new
                        {
                            Id = 12,
                            Foglalt = false,
                            Szam = 12,
                            TeremId = 1
                        },
                        new
                        {
                            Id = 13,
                            Foglalt = false,
                            Szam = 13,
                            TeremId = 1
                        },
                        new
                        {
                            Id = 14,
                            Foglalt = true,
                            Szam = 14,
                            TeremId = 1
                        },
                        new
                        {
                            Id = 15,
                            Foglalt = true,
                            Szam = 15,
                            TeremId = 1
                        },
                        new
                        {
                            Id = 16,
                            Foglalt = true,
                            Szam = 16,
                            TeremId = 1
                        },
                        new
                        {
                            Id = 17,
                            Foglalt = false,
                            Szam = 17,
                            TeremId = 1
                        },
                        new
                        {
                            Id = 18,
                            Foglalt = false,
                            Szam = 18,
                            TeremId = 1
                        },
                        new
                        {
                            Id = 19,
                            Foglalt = false,
                            Szam = 19,
                            TeremId = 1
                        },
                        new
                        {
                            Id = 20,
                            Foglalt = false,
                            Szam = 20,
                            TeremId = 1
                        },
                        new
                        {
                            Id = 8,
                            Foglalt = false,
                            Szam = 8,
                            TeremId = 1
                        },
                        new
                        {
                            Id = 21,
                            Foglalt = false,
                            Szam = 1,
                            TeremId = 2
                        },
                        new
                        {
                            Id = 22,
                            Foglalt = false,
                            Szam = 2,
                            TeremId = 2
                        },
                        new
                        {
                            Id = 23,
                            Foglalt = false,
                            Szam = 3,
                            TeremId = 2
                        },
                        new
                        {
                            Id = 24,
                            Foglalt = true,
                            Szam = 4,
                            TeremId = 2
                        },
                        new
                        {
                            Id = 25,
                            Foglalt = true,
                            Szam = 5,
                            TeremId = 2
                        },
                        new
                        {
                            Id = 26,
                            Foglalt = true,
                            Szam = 6,
                            TeremId = 2
                        },
                        new
                        {
                            Id = 27,
                            Foglalt = false,
                            Szam = 7,
                            TeremId = 2
                        },
                        new
                        {
                            Id = 28,
                            Foglalt = false,
                            Szam = 8,
                            TeremId = 2
                        },
                        new
                        {
                            Id = 29,
                            Foglalt = true,
                            Szam = 9,
                            TeremId = 2
                        },
                        new
                        {
                            Id = 30,
                            Foglalt = false,
                            Szam = 10,
                            TeremId = 2
                        },
                        new
                        {
                            Id = 31,
                            Foglalt = false,
                            Szam = 11,
                            TeremId = 2
                        },
                        new
                        {
                            Id = 32,
                            Foglalt = false,
                            Szam = 12,
                            TeremId = 2
                        },
                        new
                        {
                            Id = 33,
                            Foglalt = false,
                            Szam = 13,
                            TeremId = 2
                        },
                        new
                        {
                            Id = 34,
                            Foglalt = true,
                            Szam = 14,
                            TeremId = 2
                        },
                        new
                        {
                            Id = 35,
                            Foglalt = true,
                            Szam = 15,
                            TeremId = 2
                        },
                        new
                        {
                            Id = 36,
                            Foglalt = true,
                            Szam = 16,
                            TeremId = 2
                        },
                        new
                        {
                            Id = 37,
                            Foglalt = false,
                            Szam = 17,
                            TeremId = 2
                        },
                        new
                        {
                            Id = 38,
                            Foglalt = false,
                            Szam = 18,
                            TeremId = 2
                        },
                        new
                        {
                            Id = 39,
                            Foglalt = true,
                            Szam = 19,
                            TeremId = 2
                        },
                        new
                        {
                            Id = 40,
                            Foglalt = true,
                            Szam = 20,
                            TeremId = 2
                        },
                        new
                        {
                            Id = 41,
                            Foglalt = false,
                            Szam = 1,
                            TeremId = 3
                        },
                        new
                        {
                            Id = 42,
                            Foglalt = false,
                            Szam = 2,
                            TeremId = 3
                        },
                        new
                        {
                            Id = 43,
                            Foglalt = false,
                            Szam = 3,
                            TeremId = 3
                        },
                        new
                        {
                            Id = 44,
                            Foglalt = true,
                            Szam = 4,
                            TeremId = 3
                        },
                        new
                        {
                            Id = 45,
                            Foglalt = true,
                            Szam = 5,
                            TeremId = 3
                        },
                        new
                        {
                            Id = 46,
                            Foglalt = true,
                            Szam = 6,
                            TeremId = 3
                        },
                        new
                        {
                            Id = 47,
                            Foglalt = false,
                            Szam = 7,
                            TeremId = 3
                        },
                        new
                        {
                            Id = 48,
                            Foglalt = false,
                            Szam = 8,
                            TeremId = 3
                        },
                        new
                        {
                            Id = 49,
                            Foglalt = true,
                            Szam = 9,
                            TeremId = 3
                        },
                        new
                        {
                            Id = 50,
                            Foglalt = false,
                            Szam = 10,
                            TeremId = 3
                        },
                        new
                        {
                            Id = 51,
                            Foglalt = false,
                            Szam = 11,
                            TeremId = 3
                        },
                        new
                        {
                            Id = 52,
                            Foglalt = false,
                            Szam = 12,
                            TeremId = 3
                        },
                        new
                        {
                            Id = 53,
                            Foglalt = false,
                            Szam = 13,
                            TeremId = 3
                        },
                        new
                        {
                            Id = 54,
                            Foglalt = true,
                            Szam = 14,
                            TeremId = 3
                        },
                        new
                        {
                            Id = 55,
                            Foglalt = true,
                            Szam = 15,
                            TeremId = 3
                        },
                        new
                        {
                            Id = 56,
                            Foglalt = true,
                            Szam = 16,
                            TeremId = 3
                        },
                        new
                        {
                            Id = 57,
                            Foglalt = false,
                            Szam = 17,
                            TeremId = 3
                        },
                        new
                        {
                            Id = 58,
                            Foglalt = false,
                            Szam = 18,
                            TeremId = 3
                        },
                        new
                        {
                            Id = 59,
                            Foglalt = true,
                            Szam = 19,
                            TeremId = 3
                        },
                        new
                        {
                            Id = 60,
                            Foglalt = true,
                            Szam = 20,
                            TeremId = 3
                        });
                });

            modelBuilder.Entity("Mozi.Shared.Szinesz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("Ertekeles")
                        .HasColumnType("float");

                    b.Property<int>("FilmId")
                        .HasColumnType("int");

                    b.Property<int>("Kor")
                        .HasColumnType("int");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FilmId");

                    b.ToTable("Szineszek");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ertekeles = 9.0,
                            FilmId = 1,
                            Kor = 24,
                            Nev = "Szinesz1"
                        },
                        new
                        {
                            Id = 2,
                            Ertekeles = 4.0,
                            FilmId = 1,
                            Kor = 54,
                            Nev = "Szinesz2"
                        },
                        new
                        {
                            Id = 3,
                            Ertekeles = 1.0,
                            FilmId = 2,
                            Kor = 28,
                            Nev = "Szinesz3"
                        });
                });

            modelBuilder.Entity("Mozi.Shared.Terem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("FilmId")
                        .HasColumnType("int");

                    b.Property<string>("TeremNev")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FilmId");

                    b.ToTable("Termek");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FilmId = 1,
                            TeremNev = "Elso"
                        },
                        new
                        {
                            Id = 2,
                            FilmId = 2,
                            TeremNev = "Masodik"
                        },
                        new
                        {
                            Id = 3,
                            FilmId = 2,
                            TeremNev = "Harmadik"
                        });
                });

            modelBuilder.Entity("Mozi.Shared.Szek", b =>
                {
                    b.HasOne("Mozi.Shared.Terem", null)
                        .WithMany("Szekek")
                        .HasForeignKey("TeremId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mozi.Shared.Szinesz", b =>
                {
                    b.HasOne("Mozi.Shared.Film", null)
                        .WithMany("Szineszek")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mozi.Shared.Terem", b =>
                {
                    b.HasOne("Mozi.Shared.Film", null)
                        .WithMany("Termek")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mozi.Shared.Film", b =>
                {
                    b.Navigation("Szineszek");

                    b.Navigation("Termek");
                });

            modelBuilder.Entity("Mozi.Shared.Terem", b =>
                {
                    b.Navigation("Szekek");
                });
#pragma warning restore 612, 618
        }
    }
}
